### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by XIANGLINYUN** [kzhou23/toch#1]
你好，我在处理数据的时候遇到了这个问题，请问怎么解决呢
Starting data preprocessing !
Processing data for test split.
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "data/grab/preprocessing.py", line 329, in <module>
    GRABDataSet(args, grab_splits)
  File "data/grab/preprocessing.py", line 46, in __init__
    self.data_preprocessing(args)
  File "data/grab/preprocessing.py", line 199, in data_preprocessing
    object_data['verts'] = np.concatenate(object_data['verts'])
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

![image](https://user-images.githubusercontent.com/103312244/183618661-181ded91-c3a5-4ee2-ac61-fcf744e3a71d.png)

**Comment by kzhou23** [comment]
Hi,

I just run the preprocessing script and it worked without any problem. Can you first check if your local repository is up-to-date? I've corrected a few bugs since the first release.

**Comment by XIANGLINYUN** [comment]
> 

Could you please show me the hierarchy of the data folder

**Comment by kzhou23** [comment]
The raw GRAB hierarchy is like this:

- GRAB
    - grab
        - s1
            - *.npz 
        - s2
        - ...
        - s10  
    - tools
        - object_meshes

**Comment by XIANGLINYUN** [comment]
Hi I'm sorry for bothering again did you make some modification with objectmodel.py from GRAB?

**Comment by kzhou23** [comment]
Thanks for raising this issue! I indeed added a few lines to objectmodel.py. I will update the instructions later today.

**Comment by XIANGLINYUN** [comment]
Thank you!

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: kzhou23 ***@***.***>
发送时间: Thursday, August 11, 2022 12:39:56 PM
收件人: kzhou23/toch ***@***.***>
抄送: XIANGLINYUN ***@***.***>; Author ***@***.***>
主题: Re: [kzhou23/toch] ValueError: need at least one array to concatenate (Issue #1)


Thanks for raising this issue! I indeed added a few lines to objectmodel.py. I will update the instructions later today.

―

**Comment by kzhou23** [comment]
Can you pull the latest objectmodel.py and check if it works now?

**Comment by XIANGLINYUN** [comment]
Hi, thank you for reuploading, it works now, could please share the checkpoint file, it should take a lot time to train it.

**Comment by kzhou23** [comment]
The checkpoint will be uploaded soon.

**Comment by XIANGLINYUN** [comment]
Thank you for your reply I’ll try

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: kzhou23 ***@***.***>
发送时间: Tuesday, August 9, 2022 3:16:31 PM
收件人: kzhou23/toch ***@***.***>
抄送: XIANGLINYUN ***@***.***>; Author ***@***.***>
主题: Re: [kzhou23/toch] ValueError: need at least one array to concatenate (Issue #1)


Hi,

I just run the preprocessing script and it worked without any problem. Can you first check if your local repository is up-to-date? I've corrected a few bugs since the first release.

―
